name: financial_nlp_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.3.1
  - pip:
  - "--trusted-host"
  - "pypi.org"
  - "--trusted-host"
  - "files.pythonhosted.org"
  - -r src/requirements.txt